# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: My .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0' ]
        
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet add package Newtonsoft.Json --version 12.0.1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Publish
      run: dotnet publish --configuration Release
    - name: List files
      run: ls -R /home/runner/work/DotNetTest/DotNetTest/bin/Release/net${{ matrix.dotnet-version }} 
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: my-cool-app-on-${{ matrix.dotnet-version }}
        path: "/home/runner/work/DotNetTest/DotNetTest/bin/Release/net${{ matrix.dotnet-version }}/*"
